services:
  app:
    build: .
    container_name: rss-flask-app
    ports:
      - "5001:5000"
    volumes:
      - ./content:/app/content
      - ./db:/app/db
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1